export const POPULAR_MOVIES = 'POPULAR_MOVIES';
export const CURRENTMOVIEINFO = 'CURRENTMOVIEINFO';
export const SET_LOADING = 'SET_LOADING';
export const GET_ACTORS_CREW = 'GET_ACTORS_CREW';
export const ADD_MORE_MOVIES = 'ADD_MORE_MOVIES';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';